APM-398: Add JMeter load test scripts
inspectit-labs/spring-petclinic-microservices pull request #10
Opened 2017-11-21 11:17 UTC by tzwickl

Add JMeter load test scripts

Add JMeter load test scripts for PetClinic for Windows and Docker environments

2017-11-24 13:05 UTC, ivansenic requested changes
* I compared these two files in the KDiff3 and the only difference is in one line regarding the influxdb host name: `<stringProp name="Argument.value">influxdb</stringProp>`. Can we just have one file and the resolve this via the environment variable? So when starting test you need to provide this variable on the command line, with a fallback to localhost if the var is not provided? I think this is same as already present user defined variables?
* Can you also update the README.md file and add a section that shorty describes that there are jmeter load tests available and provide a command on how to start the load test.
* tested with Apache 3.3 and it works without any problems

2017-11-24 18:19 UTC, tzwickl commented
ok I added a new parameter INFLUXDB_HOST :)

2017-11-29 14:55 UTC, ivansenic approved these changes

2017-11-29 14:56 UTC, ivansenic commented
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/10)*
<!-- Sent from Reviewable.io -->

2017-11-29 14:56 UTC, merged